image:
  repository: ghcr.io/unesprodrigofct/machine-learning/ml-api
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  - name: ML_ENVIRONMENT
    value: "production"
  - name: ML_MLFLOW_TRACKING_URI
    value: "https://mlflow.example.com"

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

serviceAccount:
  create: true
  name: ""
